### ISSUE TITLE
Pebble Time support

### ISSUE THREAD

**Issue by zoetrope69** [bitbased/watch-fm#1]
Any plans to add colour for the Pebble Time?

**Comment by brantwedel** [comment]
I will try if the Pebble Time's bluetooth data connection is faster (sending color image data would take 4 times longer, and it's already slow for black-and-white on the original Pebble). I will wait till I get my new Pebble this month.

**Comment by zoetrope69** [comment]
Cool, if it's delayed shouldn't be too much of an issue.

**Comment by brantwedel** [comment]
Here is a teaser, haha, hopefully finishing it up this week, so far so good.

![pebble-screenshot_2015-06-24_01-00-01](https://cloud.githubusercontent.com/assets/1801892/8323613/7081fca4-1a0c-11e5-9dc1-224677e78e3f.png)

**Comment by brantwedel** [comment]
@zaccolley Just published this, let me know if there are any kinks. There was one limitation, there is not enough "persistent storage" to store the image in color, so when you change screens it has to reload the image over bluetooth when you change back.

**Comment by zoetrope69** [comment]
Sick, using it now. Will open any issues I find. :+1: :watch:
